# Generated by Django 4.0.1 on 2023-02-17 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_owner',
            new_name='user',
        ),
    ]
