# Generated by Django 4.0.1 on 2023-02-17 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_profile_owner_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='loaction',
            field=models.TextField(blank=True),
        ),
    ]
