# Generated by Django 4.0.1 on 2023-02-17 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_profile_loaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='loaction',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
