# Generated by Django 4.1.3 on 2023-02-20 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_follower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='loaction',
            field=models.TextField(blank=True),
        ),
    ]
