# Generated by Django 4.1.3 on 2023-02-20 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_profile_loaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='loaction',
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
