# Generated by Django 4.0.1 on 2023-02-21 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_profile_email_profile_firstname_profile_lastname'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='headerimage',
            field=models.ImageField(default='header.jpg', upload_to='profileimgs'),
        ),
    ]
